version: '3.7'

services:
    fastify-backbone:
        build:
            context: .
            dockerfile: Dockerfile
            target: builder
        volumes:
            - ./src:/app/src
            - ./nodemon.json:/app/nodemon.json
            - ./.env:/app/.env
        container_name: fastify-backbone
        ports:
            - '3015:8080'
        command: npm run dev
        env_file:
            - .env
